apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepare-longhorn-image
  labels:
    app: prepare-longhorn-image
  annotations:
    command: &cmd wget -q --progress=bar --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1YGXE_U5FdhvE2TdUHZBdt3QvGG391T58' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1YGXE_U5FdhvE2TdUHZBdt3QvGG391T58" -O longhorn-1.5.1-image.tar.gz && rm -rf /tmp/cookies.txt && podman load < longhorn-1.5.1-image.tar.gz && rm longhorn-1.5.1-image.tar.gz
spec:
  selector:
    matchLabels:
      app: prepare-longhorn-image
  template:
    metadata:
      labels:
        app: prepare-longhorn-image
    spec:
      hostNetwork: true
      hostPID: true
      initContainers:
      - name: prepare-longhorn-image
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - bash
          - -c
          - *cmd
        image: quay.io/cloudwalker/alpine
        securityContext:
          privileged: true
      containers:
      - name: sleep
        image: registry.k8s.io/pause:3.6
  updateStrategy:
    type: RollingUpdate
